apiVersion: v1
kind: Namespace
metadata:
  name: pg-ns
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: pg-ns
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: pg-ns
data:
  pg_hba.conf: |
    local   all             all                                     peer
    host    all             all             0.0.0.0/0            scram-sha-256
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: pg-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # В minikube по умолчанию используется storageClass "standard"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-postgres-18
  namespace: pg-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      version: "18"
  template:
    metadata:
      labels:
        app: postgres
        version: "18"
    spec:
      containers:
        - name: postgres
          image: postgres:18.3-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            # Подкаталог избегает проблем с правами доступа к смонтированному тому
            - name: PGDATA
              value: /var/lib/postgresql/18/docker
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/18
            - name: postgres-config
              mountPath: /var/lib/postgres/18/docker/pg_hba.conf
              subPath: pg_hba.conf
      volumes:
        - name: postgres-config
          configMap:
            name: postgres-config
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: pg-ns
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30432
  selector:
    app: postgres
    version: "18"