services:
  ubuntu:
    tty: true
    image: postgres:18-alpine
#    user: ubuntu
#    volumes:
#      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ['/bin/bash']
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 127.0.0.1:5432:5432



